### ISSUE TITLE
GPU not supported in the pytorch version used.

### ISSUE THREAD

**Issue by kevinbuysse** [MagnumVD/RotoForge-AI#23]
I getting this error when trying to generate. I am using a RTX5070ti (laptop) with the lastest drivers.
After some investigation it looks like the pytorch version used does not support these gpu's.

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

RotoForge Version: 1.1.1
Blender Version: 4.4.3

**Comment by kevinbuysse** [comment]
I tested with blender 4.5 and it worked with my gpu

**Comment by MagnumVD** [comment]
Perfect, thanks.
I think in that case I'll close this issue now. If any problems arise again, you can just reopen it or create a new one.
